server:
  port: 8080

spring:
  application:
    name: spring7
  datasource:
    url: jdbc:postgresql://localhost:5432/spring7
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

# JWT 커스텀 속성
app:
  jwt:
    secret: "your-256-bit-secret-your-256-bit-secret"  # 최소 256bit 이상
    issuer: "spring7"
    accessTokenValidityMs: 3600000  # 1시간 (ms)

# jwt:
#   secret: "change-me-to-a-very-long-random-32bytes-minimum-secret-string_which_is_at_least_32_bytes"
#   access-token-expiration: 3600000  # 1시간 (ms)
#   issuer: "spring7"

# CORS (필요시)
# app:
#   cors:
#     allowed-origins: "http://localhost:3000"
